"""empty message

Revision ID: 063dfc5b5444
Revises: d024e1ebcbae
Create Date: 2017-05-02 08:17:30.262302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063dfc5b5444'
down_revision = 'd024e1ebcbae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('lab')

    # ### end Alembic commands ###
