"""empty message

Revision ID: 0be5c43c0a7b
Revises: 5af30691e939
Create Date: 2017-04-26 14:42:40.249127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be5c43c0a7b'
down_revision = '5af30691e939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chip_form', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('datasheet_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('packaging_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('datasheet_id', 'documents', ['datasheet_id'], ['id'])
        batch_op.drop_column('packaging_type')
        batch_op.drop_column('type')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.Text(), nullable=True))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.TEXT(), nullable=True))
        batch_op.drop_column('file_name')

    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('packaging_type', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('packaging_id')
        batch_op.drop_column('datasheet_id')
        batch_op.drop_column('chip_form')

    # ### end Alembic commands ###
