"""empty message

Revision ID: 2bf590d75e79
Revises: 6f291ad661a6
Create Date: 2017-04-21 09:56:39.172041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf590d75e79'
down_revision = '6f291ad661a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('housing_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('smd', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_column('smd')
        batch_op.drop_column('housing_id')
        batch_op.drop_column('description')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
