"""empty message

Revision ID: 302ed0027f3b
Revises: 
Create Date: 2017-04-20 17:18:20.567069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302ed0027f3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('project_name', sa.Text(), nullable=True))
    op.add_column('booking', sa.Column('user_mail', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'booking', 'project', ['project_name'], ['project_name'])
    op.add_column('component', sa.Column('manufacturer_id', sa.Text(), nullable=True))
    op.drop_constraint(None, 'component', type_='foreignkey')
    op.drop_column('component', 'exb_number')
    op.add_column('exb', sa.Column('associated_components_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exb', 'component', ['associated_components_id'], ['id'])
    op.add_column('reservation', sa.Column('user_mail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'user_mail')
    op.drop_constraint(None, 'exb', type_='foreignkey')
    op.drop_column('exb', 'associated_components_id')
    op.add_column('component', sa.Column('exb_number', sa.TEXT(), nullable=True))
    op.create_foreign_key(None, 'component', 'exb', ['exb_number'], ['exb_number'])
    op.drop_column('component', 'manufacturer_id')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_column('booking', 'user_mail')
    op.drop_column('booking', 'project_name')
    # ### end Alembic commands ###
