"""empty message

Revision ID: 4498a263028a
Revises: 302ed0027f3b
Create Date: 2017-04-20 17:56:32.580114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4498a263028a'
down_revision = '302ed0027f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'project', ['project_name'], ['project_name'])

    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('exb_number')

    with op.batch_alter_table('exb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('associated_components_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'component', ['associated_components_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exb', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('associated_components_id')

    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exb_number', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(None, 'exb', ['exb_number'], ['exb_number'])

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
