"""empty message

Revision ID: 5af30691e939
Revises: 2bf590d75e79
Create Date: 2017-04-24 14:31:44.194606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af30691e939'
down_revision = '2bf590d75e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
