"""empty message

Revision ID: 6e07f3f40906
Revises: 063dfc5b5444
Create Date: 2017-05-24 19:50:18.331106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e07f3f40906'
down_revision = '063dfc5b5444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documents_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('datasheet_id', type_='foreignkey')
        batch_op.create_foreign_key('documents_id', 'documents', ['documents_id'], ['id'])
        batch_op.drop_column('datasheet_id')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_type', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('document_type')

    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datasheet_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('datasheet_id', 'documents', ['datasheet_id'], ['id'])
        batch_op.drop_column('documents_id')

    # ### end Alembic commands ###
