"""empty message

Revision ID: 6f291ad661a6
Revises: 51285514051b
Create Date: 2017-04-20 18:11:43.015758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f291ad661a6'
down_revision = '51285514051b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('associated_components_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('foreign key', 'component', ['associated_components_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exb', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('associated_components_id')

    # ### end Alembic commands ###
