"""empty message

Revision ID: d024e1ebcbae
Revises: eb4d4c172e56
Create Date: 2017-04-26 17:37:29.263172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd024e1ebcbae'
down_revision = 'eb4d4c172e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taken_out', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_column('taken_out')

    # ### end Alembic commands ###
