"""empty message

Revision ID: e1261e65e6e6
Revises: 4498a263028a
Create Date: 2017-04-20 17:58:57.318031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1261e65e6e6'
down_revision = '4498a263028a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'booking', 'project', ['project_name'], ['project_name'])
    op.drop_constraint(None, 'component', type_='foreignkey')
    op.drop_column('component', 'exb_number')
    op.add_column('exb', sa.Column('associated_components_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exb', 'component', ['associated_components_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exb', type_='foreignkey')
    op.drop_column('exb', 'associated_components_id')
    op.add_column('component', sa.Column('exb_number', sa.TEXT(), nullable=True))
    op.create_foreign_key(None, 'component', 'exb', ['exb_number'], ['exb_number'])
    op.drop_constraint(None, 'booking', type_='foreignkey')
    # ### end Alembic commands ###
