"""empty message

Revision ID: eb4d4c172e56
Revises: 0be5c43c0a7b
Create Date: 2017-04-26 15:27:15.903911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4d4c172e56'
down_revision = '0be5c43c0a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chip_form_id', sa.Text(), nullable=True))
        batch_op.drop_column('chip_form')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chip_form', sa.TEXT(), nullable=True))
        batch_op.drop_column('chip_form_id')

    # ### end Alembic commands ###
